apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportfolio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myportfolio
  template:
    metadata:
      labels:
        app: myportfolio
    spec:
      containers:
      - name: myportfolio
        image: akashshewale0801/myportfolio:latest  # Using latest tag
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: myportfolio-service
spec:
  selector:
    app: myportfolio
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
